[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:806 Connecting to existing model concierge-lxd:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:33 Deploying charms
[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:postgresql-0
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/noble/data-integrator-180
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:47 Adding relation between charms
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [allocating] waiting: waiting for machine
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [allocating] waiting: waiting for machine
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [executing] waiting: agent initialising
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [allocating] waiting: waiting for machine
  postgresql/1 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [executing] maintenance: installing PostgreSQL
  postgresql/1 [executing] active: Primary (degraded)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] blocked: Please relate the data-integrator with the desired product
  postgresql/0 [executing] waiting: waiting to start PostgreSQL
  postgresql/1 [executing] active: Primary (degraded)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] active: 
  postgresql/0 [idle] waiting: waiting to start PostgreSQL
  postgresql/1 [executing] active: Primary (degraded)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql/0 [idle] waiting: waiting to start PostgreSQL
  postgresql/1 [executing] maintenance: reconfiguring cluster
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql/0 [executing] waiting: waiting to start PostgreSQL
  postgresql/1 [executing] maintenance: reconfiguring cluster
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [idle] active: 
  postgresql/0 [idle] maintenance: reinitialising replica
  postgresql/1 [executing] active: Primary
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql/1 [executing] active: Primary
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:78 Dropping database objects from the previous test run (if any)
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:91 Creating database objects needed for the test
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:113 Checking that the user relation_id_0 can connect to the database test_1 on postgresql/0
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:135 Checking that the user relation_id_1 can connect to the database test_2 on postgresql/0
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:155 Checking that the user relation_id_1 cannot connect to the database test_1 on postgresql/0
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:113 Checking that the user relation_id_0 can connect to the database test_1 on postgresql/1
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:135 Checking that the user relation_id_1 can connect to the database test_2 on postgresql/1
[32mINFO    [0m integration.test_pg_hba:test_pg_hba.py:155 Checking that the user relation_id_1 cannot connect to the database test_1 on postgresql/1
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.9    unsupported  01:41:42Z

App              Version  Status  Scale  Charm            Channel        Rev  Exposed  Message
data-integrator           active      1  data-integrator  latest/stable  180  no       
postgresql       14.18    active      2  postgresql                        0  no       

Unit                Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*  active    idle   2        10.84.205.102             
postgresql/0        active    idle   0        10.84.205.226   5432/tcp  
postgresql/1*       active    idle   1        10.84.205.196   5432/tcp  Primary

Machine  State    Address        Inst id        Base          AZ             Message
0        started  10.84.205.226  juju-d14c8d-0  ubuntu@22.04  runnervmf4ws1  Running
1        started  10.84.205.196  juju-d14c8d-1  ubuntu@22.04  runnervmf4ws1  Running
2        started  10.84.205.102  juju-d14c8d-2  ubuntu@24.04  runnervmf4ws1  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

machine-2: 01:34:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:34:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:34:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:35:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:35:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:35:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:36:18 ERROR unit.postgresql/1.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 494, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 325, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5c339cc700>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.84.205.196', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c339cc700>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 577, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 677, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.84.205.196', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c339cc700>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-postgresql-1: 01:36:29 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

machine-0: 01:36:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:36:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:36:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...