[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:544 starting continuous writes to the database
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:547 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:103 Initial writes {'test.postgresql-0': 219, 'test.postgresql-1': 219}
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:113 Retry writes {'test.postgresql-0': 376, 'test.postgresql-1': 376}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:551 scaling out the first cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: Primary
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [executing] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [executing] maintenance: installing PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] maintenance: reconfiguring cluster
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: Primary
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [executing] maintenance: reconfiguring cluster
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: Primary
  postgresql/3 [executing] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [executing] active: 
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/1 [idle] active: Primary
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: Primary
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: Primary
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:555 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:103 Initial writes {'test.postgresql-0': 24719, 'test.postgresql-1': 24719, 'test-other.postgresql-0': 24720, 'test-other.postgresql-1': 24721}
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:113 Retry writes {'test.postgresql-0': 24853, 'test.postgresql-1': 24854, 'test-other.postgresql-0': 24854, 'test-other.postgresql-1': 24855}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:558 scaling out the second cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: Standby
  postgresql/2 [idle] active: 
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [executing] maintenance: installing PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [executing] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [executing] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: Standby
  postgresql/2 [executing] active: 
  postgresql/3 [executing] waiting: waiting to start PostgreSQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] maintenance: reconfiguring cluster
  postgresql/2 [idle] active: 
  postgresql/3 [executing] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: Standby
  postgresql/2 [executing] active: 
  postgresql/3 [executing] waiting: Waiting for the database to start
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: Standby
  postgresql/2 [executing] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [executing] active: Standby
  postgresql/2 [executing] active: 
  postgresql/3 [executing] waiting: waiting for primary to be reachable from this unit
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/0 [idle] active: Standby
  postgresql/2 [idle] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:564 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:103 Initial writes {'test.postgresql-0': 48092, 'test.postgresql-1': 48092, 'test-other.postgresql-0': 48093, 'test-other.postgresql-1': 48093}
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:113 Retry writes {'test.postgresql-0': 48231, 'test.postgresql-1': 48232, 'test-other.postgresql-0': 48232, 'test-other.postgresql-1': 48232}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:567 scaling in the first cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql (waiting for exactly 2 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql (waiting for exactly 2 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/1 [executing] active: Primary
  postgresql/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/1 [executing] active: Primary
  postgresql/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/1 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:570 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:103 Initial writes {'test.postgresql-1': 54581, 'test.postgresql-3': 54582, 'test-other.postgresql-1': 54583, 'test-other.postgresql-3': 54584}
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:113 Retry writes {'test.postgresql-1': 54856, 'test.postgresql-3': 54856, 'test-other.postgresql-1': 54856, 'test-other.postgresql-3': 54857}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:573 scaling in the second cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql (waiting for exactly 2 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/2 [idle] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/2 [executing] active: 
  postgresql/3 [executing] maintenance: reconfiguring cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/2 [idle] active: 
  postgresql/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  postgresql/2 [idle] active: 
  postgresql/3 [idle] active: Standby
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:578 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:103 Initial writes {'test.postgresql-1': 63337, 'test.postgresql-3': 63338, 'test-other.postgresql-1': 63340, 'test-other.postgresql-3': 63340}
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:113 Retry writes {'test.postgresql-1': 63479, 'test.postgresql-3': 63479, 'test-other.postgresql-1': 63480, 'test-other.postgresql-3': 63481}
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:583 checking whether no writes were lost
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:82 Destroying second model
[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.6    unsupported  02:54:48Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
data-integrator               active      1  data-integrator      latest/edge   80  no       
postgresql           14.13    active      2  postgresql                          0  no       Primary
postgresql-test-app           active      1  postgresql-test-app  latest/edge  305  no       received database credentials of the first database

Unit                    Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*      active    idle   3        10.173.177.145            
postgresql-test-app/0*  active    idle   4        10.173.177.155            received database credentials of the first database
postgresql/1*           active    idle   1        10.173.177.67   5432/tcp  Primary
postgresql/3            active    idle   5        10.173.177.110  5432/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.173.177.67   juju-d15d77-1  ubuntu@22.04      Running
3        started  10.173.177.145  juju-d15d77-3  ubuntu@22.04      Running
4        started  10.173.177.155  juju-d15d77-4  ubuntu@22.04      Running
5        started  10.173.177.110  juju-d15d77-5  ubuntu@22.04      Running

Offer              Application  Charm       Rev  Connected  Endpoint           Interface         Role
replication        postgresql   postgresql  0    0/0        replication        postgresql_async  requirer
replication-offer  postgresql   postgresql  0    1/1        replication-offer  postgresql_async  provider

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-1: 01:42:40 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:42:40 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:42:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:42:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:42:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:42:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:42:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:42:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:42:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:42:54 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:42:54 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:42:56 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:44:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:44:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:44:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:45:23 ERROR unit.postgresql/1.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc14f7591b0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.173.177.67', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc14f7591b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.173.177.67', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc14f7591b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-postgresql-1: 02:03:27 ERROR unit.postgresql/1.juju-log database-peers:1: Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdc98b361a0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.173.177.67', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc98b361a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.173.177.67', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc98b361a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-postgresql-2: 02:14:32 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f": settings 6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f not found (not found)
unit-postgresql-0: 02:14:33 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f": settings 6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f not found (not found)
unit-postgresql-1: 02:14:34 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f": settings 6c755659-eec2-4e50-8ebb-5882b5d15d77:r#7#remote-53264b8861f842548f48701edcea0d5f not found (not found)
machine-5: 02:35:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:35:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-3: 02:35:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk

[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...